var keymirror = require("react/lib/keymirror");

module.exports = keymirror({
  LOAD_SHOW: "LOAD_SHOW",
  LOAD_SHOW_SUCCESS: "LOAD_SHOW_SUCCESS",
  LOAD_SHOW_FAILURE: "LOAD_SHOW_FAILURE",

  LOAD_SHOWS: "LOAD_SHOWS",
  LOAD_SHOWS_SUCCESS: "LOAD_SHOWS_SUCCESS",
  LOAD_SHOWS_FAILURE: "LOAD_SHOWS_FAILURE"
});
